class Occupation < ActiveHash::Base
  self.data = [
    {id: 1, name: '---'},
    {id: 2, name: '大工'},
    {id: 3, name: '型枠大工'},
    {id: 4, name: '左官'},
    {id: 5, name: 'とび工'},
    {id: 6, name: '板金工'},
    {id: 7, name: '石工'},
    {id: 8, name: '建具工'},
    {id: 9, name: '表具工'},
    {id: 10, name: '塗装工'},
    {id: 11, name: '電工'},
    {id: 12, name: '配管工'},
    {id: 13, name: '屋根葺工'},
    {id: 14, name: 'ブロック積工'},
    {id: 15, name: '畳工'},
    {id: 16, name: '木工'},
    {id: 17, name: 'タイル張工'},
    {id: 18, name: '造園工'},
    {id: 19, name: '土工'},
    {id: 20, name: '手伝'},
    {id: 21, name: '下地工'},
    {id: 22, name: '防水工'},
    {id: 23, name: 'コンクリート工'},
    {id: 24, name: '内装工'},
    {id: 25, name: '外装工'},
    {id: 26, name: '家洗工'},
    {id: 27, name: '配筋工'},
    {id: 28, name: '鉄骨工'},
    {id: 29, name: '鉄工'},
    {id: 30, name: 'レンガ積工'},
    {id: 31, name: 'ハツリ工'},
    {id: 32, name: '解体工'},
    {id: 33, name: '床張工'},
    {id: 34, name: 'ガラス工'},
    {id: 35, name: 'サッシ工'},
    {id: 36, name: 'シャッター工'},
    {id: 37, name: '昇降機組立工'},
    {id: 38, name: '屋根組立工'},
    {id: 39, name: '附帯設備工'},
    {id: 40, name: 'さく井工'},
    {id: 41, name: '設計工'},
    {id: 42, name: '製図工'},
    {id: 43, name: '建設海事工'},
    {id: 44, name: '建築製罐工'},
    {id: 45, name: '建築防虫工'},
    {id: 46, name: '建設機械運転工'},
    {id: 47, name: '自動車運転手'},
    {id: 48, name: '現場監督'},
    {id: 49, name: '雑役'},
    {id: 50, name: '建築事務'},
    {id: 51, name: '天井張工'},
    {id: 52, name: '空調設備工'},
    {id: 53, name: '家曳工'},
    {id: 54, name: 'その他'}
  ]

  include ActiveHash::Associations
  has_many :organizations

end

  
